export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  FEED: "Feed",
  MYITEMS: "MyItems",
  USERUPDATE: "UserUpdate",
  ACCOUNT: "Accountt",
  ITEMUPDATE: "ItemUpdate",
  CONTACT: "Contact",
  MESSAGEDETAIL: "MessageDetail",
  LISTINGS: "Listings",
  INTERESTS: "SuscribedItems",
  LISTINGDETAILS: "ListingDetails",
});
